# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

RUN apt-get update

RUN mkdir src
RUN mkdir tests

ENV PYTHONPATH=/app/src:/app/tests

# Install default packages. Unfortunately, this includes pydraw.
RUN pip install --no-cache-dir pydraw 