# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Install system dependencies including TKinter and xvfb
RUN apt-get update && apt-get install -y \
    python3-tk \
    xvfb \
    && rm -rf /var/lib/apt/lists/*

# Create necessary directories
RUN mkdir src
RUN mkdir tests

# Set Python path
ENV PYTHONPATH=/app/src:/app/tests

# Install Python packages
RUN pip install --no-cache-dir pydraw