name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Pull latest changes and install requirements on server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SSH_HOST }} << 'EOF'
            #  Pull repository changes
            cd IDE-autograder
            git pull origin main

            # Set up the virtual environment and install requirements
            python3 -m venv autograder_venv
            source autograder_env/bin/activate
            pip install -r requirements.txt
          EOF

      - name: Rebuilding docker images
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SSH_HOST }} << 'EOF'
            # Remove pre-existing images
            docker image prune -a -f

            # Rebuild all docker images
            for dockerfile in /dockerfiles/*; do
              docker build -f $dockerfile -t $(basename $dockerfile .Dockerfile) .
            done
          EOF

      - name: Restart FastAPI application
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SSH_HOST }} << 'EOF'
            sudo systemctl restart fastapi
          EOF
