# name: Deploy to EC2

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Setup SSH
#         uses: webfactory/ssh-agent@v0.5.3
#         with:
#           ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

#       - name: Copy app directory to server
#         run: |
#           rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./app/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/path/to/remote/app/
